export const rows = [
  {
    id: 1,
    title: "Jon Snow",
    description: "desc... shbsdv bqdfb vldkfvlkfv kkjv kj bnkljf vkv bbalvaekv fvbaekffbaeo fvvbeefbeh ffvbzefvber lkkbzezbe efvnbbvebvae vaejhebetgt rbeberhk bvhb slimani amin mohamed amiine slimani  rk softyline alternant",
    age: 35,
    status: false,
  },
  {
    id: 2,
    title: "Cersei Lannister",
    description: "desc",
    age: 42,
    status: true,
  },
  {
    id: 3,
    title: "Jaime Lannister",
    description: "desc...",
    age: 45,
    status: false,
  },
  {
    id: 4,
    title: "Anya Stark",
    description: "desc...",
    age: 16,
    status: false,
  },
  {
    id: 5,
    title: "Daenerys Targaryen",
    description: "desc...",
    age: 31,
    status: false,
  },
  {
    id: 6,
    title: "Ever Melisandre",
    description: "desc...",
    age: 150,
    status: false,
  },
  {
    id: 7,
    title: "Ferrara Clifford",
    description: "desc...",
    age: 44,
    status: false,
  },
  {
    id: 8,
    title: "Rossini Frances",
    description: "desc...",
    age: 36,
    status: false,
  },
  {
    id: 9,
    title: "Harvey Roxie",
    description: "desc...",
    age: 65,
    status: false,
  },
];
