export const rows = [
  {
    id:1,
    role: "user",
    name: "Raimondo",
    lastName: "Lapthorne",
    buisnessName: "Brussels Sprout",
    email: "rlapthorne0@deliciousdays.com",
    dateOfBirth: "11/22/1986",
    password: "lE8=l>%/E",
    billingAddress: "5984 Schiller Circle",
    shippingAddress: "01018 Melby Terrace",
    shippingInfo: "Other bursal cyst, unspecified hand",
  },
  {
    id:2,
    role: "admin",
    name: "amine",
    lastName: "slimani",
    buisnessName: "slimani",
    email: "slimaniamin76@gmail.com",
    dateOfBirth: "7/16/2003",
    password: "123456",
    billingAddress: "0 Eagan Trail",
    shippingAddress: "13498 Bartelt Park",
    shippingInfo: "Dislocation of unspecified part of thorax, sequela",
  },
  {
    id:3,
    role: "crafter",
    name: "Hinze",
    lastName: "Strasse",
    buisnessName: "BestHealth Honey Lemon",
    email: "hstrasse2@slate.com",
    dateOfBirth: "6/17/2000",
    password: "uT2@7aAy",
    billingAddress: "1 Mitchell Parkway",
    shippingAddress: "05665 Crescent Oaks Park",
    shippingInfo: "Contusion of left little finger w damage to nail, subs",
  },
  {
    id:5,
    role: "user",
    name: "Mair",
    lastName: "Macias",
    buisnessName: "Umecta Mousse",
    email: "mmacias3@sun.com",
    dateOfBirth: "1/18/2011",
    password: "nN4/`BkMF\\m'",
    billingAddress: "7 Michigan Hill",
    shippingAddress: "4119 Mayer Avenue",
    shippingInfo: "Toxic effect of contact w oth jellyfish, accidental",
  },
  {
    id:6,
    role: "user",
    name: "Alli",
    lastName: "Thurlow",
    buisnessName: "Pravastatin Sodium",
    email: "athurlow4@multiply.com",
    dateOfBirth: "10/6/1997",
    password: "eF3(wSV+",
    billingAddress: "8432 American Ash Pass",
    shippingAddress: "1709 Vidon Parkway",
    shippingInfo: "Contusion of ureter, initial encounter",
  },
  {
    id:7,
    role: "admin",
    name: "Joelly",
    lastName: "Dallywater",
    buisnessName: "Degree",
    email: "jdallywater5@instagram.com",
    dateOfBirth: "1/7/1981",
    password: "eT6$jRt|O=U|9",
    billingAddress: "41572 Carey Lane",
    shippingAddress: "3292 Cody Trail",
    shippingInfo: "Breakdown (mechanical) of artificial heart, sequela",
  },
  {
    id:8,
    role: "crafter",
    name: "Erena",
    lastName: "Winspire",
    buisnessName: "Antipyrine and Benzocaine",
    email: "ewinspire6@slideshare.net",
    dateOfBirth: "1/19/1995",
    password: "uO9)<k8WqE_B",
    billingAddress: "04132 Merrick Street",
    shippingAddress: "276 Corben Road",
    shippingInfo: "Infective myositis, unspecified foot",
  },
  {
    id:9,
    role: "Estimator",
    name: "Brewer",
    lastName: "Laws",
    buisnessName: "Finasteride",
    email: "blaws7@parallels.com",
    dateOfBirth: "1/15/1987",
    password: "gZ5*>=dP38DDSf7",
    billingAddress: "56 Del Mar Terrace",
    shippingAddress: "6777 Lakeland Circle",
    shippingInfo:
      "Unsp physl fx low end rad, right arm, subs for fx w malunion",
  },
  {
    id:10,
    role: "crafter",
    name: "Mei",
    lastName: "Lavell",
    buisnessName: "Drosera Homaccord",
    email: "mlavell8@timesonline.co.uk",
    dateOfBirth: "2/14/2013",
    password: "xR8|A4eVV'4t*",
    billingAddress: "9 South Pass",
    shippingAddress: "840 Fairfield Street",
    shippingInfo: "Foreign body in bladder, sequela",
  },
  {
    id:11,
    role: "user",
    name: "Dallas",
    lastName: "Jacobbe",
    buisnessName: "Cefdinir",
    email: "djacobbe9@narod.ru",
    dateOfBirth: "2/6/1954",
    password: "sP3%D84ZdR#%YN",
    billingAddress: "5402 Annamark Drive",
    shippingAddress: "61 Gina Parkway",
    shippingInfo: "Milt op w indirect blast effect of nuclear weapon, civilian",
  },
  {
    id:12,
    role: "user",
    name: "Steffie",
    lastName: "McKennan",
    buisnessName: "Heparin Sodium in Dextrose",
    email: "smckennana@lycos.com",
    dateOfBirth: "5/18/1973",
    password: "tA9}taz%c%6*X<u",
    billingAddress: "6 Lawn Lane",
    shippingAddress: "9 Browning Way",
    shippingInfo: "Disp fx of base of 5th MC bone. l hand, 7thK",
  },
  {
    id:13,
    role: "admin",
    name: "Loni",
    lastName: "Ambroz",
    buisnessName: "CAPTOPRIL",
    email: "lambrozb@archive.org",
    dateOfBirth: "7/31/2012",
    password: "cL2|aZE/m|~sp/S6",
    billingAddress: "8 Knutson Street",
    shippingAddress: "0422 Mandrake Junction",
    shippingInfo: "Toxic effect of paints and dyes, NEC, accidental, subs",
  },
  {
    id:14,
    role: "user",
    name: "Ambur",
    lastName: "Heisham",
    buisnessName: "OXYBUTYNIN CHLORIDE",
    email: "aheishamc@accuweather.com",
    dateOfBirth: "3/20/2000",
    password: "pO2.c~9z|0s",
    billingAddress: "0 Oak Hill",
    shippingAddress: "33 Kinsman Court",
    shippingInfo: "Oth fx lower end of r tibia, subs for clos fx w routn heal",
  },
  {
    id:15,
    role: "user",
    name: "Nicholle",
    lastName: "Privost",
    buisnessName: "HEALTHMART NICOTINE TRANSDERMAL SYSTEM",
    email: "nprivostd@delicious.com",
    dateOfBirth: "7/10/1976",
    password: "nB6~dWAc",
    billingAddress: "920 Truax Lane",
    shippingAddress: "5159 Golf Circle",
    shippingInfo: "Niemann-Pick disease type C",
  },
  {
    id:16,
    role: "user",
    name: "Keeley",
    lastName: "Tezure",
    buisnessName: "Shopko Antibacterial Foaming Hand Sanitizer",
    email: "ktezuree@mozilla.com",
    dateOfBirth: "4/29/1989",
    password: "pY5+~pUtqj?>!I",
    billingAddress: "69 American Ash Road",
    shippingAddress: "45355 Lawn Way",
    shippingInfo: "Corrosion of other parts of respiratory tract, subs encntr",
  },
  {
    id:16,
    role: "crafter",
    name: "Lydie",
    lastName: "Baguley",
    buisnessName: "Pollens - Weeds, Weed mix 2630",
    email: "lbaguleyf@trellian.com",
    dateOfBirth: "8/15/1986",
    password: 'mM1"Km"f6uRd"',
    billingAddress: "5320 Raven Lane",
    shippingAddress: "57 Veith Hill",
    shippingInfo: "Contusion of scrotum and testes",
  },
  {
    id:17,
    role: "user",
    name: "Jessamyn",
    lastName: "Tooby",
    buisnessName: "Quack Grass",
    email: "jtoobyg@who.int",
    dateOfBirth: "9/21/1972",
    password: 'iB6"bsue9V>,in',
    billingAddress: "93 Hooker Road",
    shippingAddress: "3512 Shopko Parkway",
    shippingInfo:
      "Injury of digital nerve of right thumb, subsequent encounter",
  },
  {
    id:18,
    role: "user",
    name: "Eric",
    lastName: "Riddington",
    buisnessName: "good sense antacid",
    email: "eriddingtonh@ca.gov",
    dateOfBirth: "2/19/2010",
    password: 'lE4(31p$&8ah.s"c',
    billingAddress: "1503 Sunbrook Plaza",
    shippingAddress: "42585 Merrick Park",
    shippingInfo: "Shock due to being struck by lightning, initial encounter",
  },
  {
    id:19,
    role: "crafter",
    name: "Baillie",
    lastName: "Eveque",
    buisnessName: "Allergy Rescue",
    email: "bevequei@ehow.com",
    dateOfBirth: "7/6/1982",
    password: "sX8`V&oo1i",
    billingAddress: "786 Caliangt Plaza",
    shippingAddress: "4775 Mifflin Park",
    shippingInfo: "Adverse effect of saline and osmotic laxatives, sequela",
  },
  {
    id:20,
    role: "crafter",
    name: "Leeland",
    lastName: "Sapwell",
    buisnessName: "Alumina",
    email: "lsapwellj@mail.ru",
    dateOfBirth: "12/24/1988",
    password: "oJ4*k52Vb",
    billingAddress: "1 Maywood Way",
    shippingAddress: "97778 Forest Center",
    shippingInfo: "Corneal abscess, right eye",
  },
];
